name: Build and push the tagged build to production

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image
    steps:
      - uses: actions/checkout@v3
      - name: Install Helm
        uses: Azure/setup-helm@v3
        with:
          version: latest
      - name: Get AKS Credentials
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Resource group name
          resource-group: CS_Infrastructure_AKS
          # AKS cluster name
          cluster-name: Infrastructure
      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace production \
            katzstunnel \
            ./kubernetes/katzstunnel
